id: P1813CF7A
initial_creation_type: input
source_metadata:
  title: Tulku Thondup
  language: fr
  description: 'Texts by and about Tulku Thondup (sprul sku don grub, b. 1939):'
  volume:
    21b7662a9c924f39a3fa8e471599cba9:
      title: Prayer for the Long Life of Tulku Thondup Rinpoche
      parent: Long Life Prayers
created_at: '2022-03-01T01:57:48.611251'
last_modified_at: '2022-03-01T01:57:48.611253'
